### ISSUE TITLE
Consideration for JSON files for 1.13+

### ISSUE THREAD

**Issue by actuallyasmartname** [thexaero/Better-PVP-Translations#11]
Since 1.13+ changes the language file extension to .lang to .json, is there any consideration for 1.13+ JSON files?

**Comment by Greg-21** [comment]
+1
This is something I've been waiting to see at some point, but maybe better sooner rather than later. A lot of text editors have syntax highlighting for JSON files, which IMO really makes the translation process easier, while `.lang` files are treated as plain text, so no syntax highlighting for them.

Xaero96, how difficult would it be for you to rewrite your `.lang` to JSON converter (or find one on the Internet instead) to work in the opposite direction?

**Comment by Greg-21** [comment]
+1
This is something I've been waiting to see at some point, but maybe better sooner rather than later. A lot of text editors have syntax highlighting for JSON files, which IMO really makes the translation process easier, while `.lang` files are treated as plain text, so no syntax highlighting for them.

Xaero96, how difficult would it be for you to rewrite your `.lang` to JSON converter (or find one on the Internet instead) to work in the opposite direction?

P.S. To keep the repository simple, I think that only one format should be chosen — the obsolete `.lang` or the current JSON.

**Comment by actuallyasmartname** [comment]
I've already got a handful of converted JSON files, so if Xaero96 does want JSON files then I could gladly open a PR for it

**Comment by thexaero** [comment]
Converting from lang to json is not a problem. How do you think I'm using the translations in 1.13+?
I chose to stick to the lang format in the repo because I feel like it's a much more accessible format to work with. JSON syntax being highlighted isn't really an argument when LANG files don't even need highlighting. It is a lot easier to mess up a JSON file.

**Comment by actuallyasmartname** [comment]
I see.

**Comment by Greg-21** [comment]
So it seems that I'm different from other people as working with JSON-formatted files is more convenient to me. Maybe because I got used to it or so...

**Comment by Greg-21** [comment]
So it seems that I'm different from other people as working with JSON-formatted files is more convenient to me. Maybe because I simply got used to it or so...

**Comment by actuallyasmartname** [comment]
> So it seems that I'm different from other people as working with JSON-formatted files is more convenient to me. Maybe because I simply got used to it or so...

I've been modding Minecraft since 1.16.3 and didn't have any plans for backporting to 1.12.2 or under, so I'm pretty much a JSON guy.

**Comment by thexaero** [comment]
I am not saying that working with JSON files is particularly difficult. But just put yourself into shoes of somebody who knows nothing about .lang or .json files. One of them is clearly more accessible than the other. Since I need to use both formats for my wide range of supported Minecraft versions, I see LANG as the better option for now. I might switch to JSON when I no longer support any MC versions that still use LANG.

**Comment by actuallyasmartname** [comment]
Alright then!
